FROM node:alpine
MAINTAINER YinChangsheng <yinchangsheng@gmail.com>

RUN apk update && apk add tar

ADD . /tmp/build

WORKDIR /tmp/build

# 1. 安装依赖
RUN npm install --registry=https://registry.npm.taobao.org

# 2. 执行构建
RUN npm run build

# 3. 拷贝编译结果到指定目录
RUN mv dist /dist && mv static/* /dist

# 4. 打包生成 zip 文件
RUN cd / && tar zcf dist.tgz /dist/*

# 5. 移除无用文件
RUN cd / && rm -rf /tmp/build

CMD ["node"]
